Test reusable workflows

diff --git a/.github/workflows/test_ecosystem.yml b/.github/workflows/test_ecosystem.yml
--- a/.github/workflows/test_ecosystem.yml
+++ b/.github/workflows/test_ecosystem.yml
@@ -1,4 +1,4 @@
-name: Test ecosystem
+name: Test ecosystem with individual badges
 
 on:
   push:
@@ -9,41 +9,103 @@ on:
         required: False
         default: ''
 
+
 jobs:
   test_ecosystem:
-    name: numpy-${{ matrix.numpy-version }}-${{ matrix.dependent-packages }}
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        numpy-version: [ 1.25, 2.1 ]
-        dependent-packages: [ 'ms2deepscore', 'ms2query', 'spec2vec' ]
-    outputs:
-      json-path: result.json
+    uses: ./.github/workflows/test_dependency.yml
+    with:
+      numpy-version: 1.25
+      dependent-packages: "spec2vec"
+    secrets: inherit
 
-    steps:
-      - uses: actions/checkout@v4
+#jobs:
+#  test_ecosystem:
+#    name: Test ecosystem / numpy-${{ matrix.numpy-version }} / ${{ matrix.dependent-packages }}
+#    runs-on: ubuntu-latest
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        numpy-version: [1.25, 2.1]
+#        dependent-packages: ["package1", "package2"]
+#    steps:
+#      - uses: actions/checkout@v4
+#
+#      - name: Set up Python
+#        uses: actions/setup-python@v5
+#        with:
+#          python-version: '3.11'
+#
+#      - name: Install dependent packages
+#        run: |
+#          python -m pip install --upgrade pip poetry
+#          pip install numpy==${{ matrix.numpy-version }}
+#          pip install ${{ matrix.dependent-packages }}
+#          pip install .
+#          pip check
+#
+#      - name: Generate Badge Status
+#        run: |
+#          mkdir -p badges
+#          echo "{ \"schemaVersion\": 1, \"label\": \"numpy-${{ matrix.numpy-version }}\", \"message\": \"$([[ ${{ success() }} == 'true' ]] && echo success || echo failure)\", \"color\": \"$([[ ${{ success() }} == 'true' ]] && echo green || echo red)\" }" > badges/numpy-${{ matrix.numpy-version }}-${{ matrix.dependent-packages }}.json
+#
+#      - name: Upload Badge Artifacts
+#        uses: actions/upload-artifact@v4
+#        with:
+#          name: badge-numpy-${{ matrix.numpy-version }}-${{ matrix.dependent-packages }}
+#          path: badges/numpy-${{ matrix.numpy-version }}-${{ matrix.dependent-packages }}.json
+#
+#
+#
+#
+##jobs:
+#  test_ecosystem:
+#    runs-on: ubuntu-latest
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        numpy-version: [ 1.25, 2.1 ]
+#        dependent-packages: [ 'ms2deepscore', 'ms2query', 'spec2vec' ]
+#    steps:
+#      - name: Trigger sub-jobs
+#        run: |
+#          echo "Creating separate jobs for each matrix combination"
+#        id: trigger
 
-      - name: Set up Python
-        uses: actions/setup-python@v5
-        with:
-          python-version: '3.11'
-
-      - name: Install dependent packages
-        run: |
-          python -m pip install --upgrade pip poetry
-          pip install numpy==${{ matrix.numpy-version }}
-          pip install ${{ matrix.dependent-packages }}
-          pip install .
-          pip check
-
-      - name: Show pip list
-        run: |
-          pip list
-
-      - name: Create Badge URLs
-        run: |
-          echo "badge_url=https://github.com/julianpollmann/matchms/actions/workflows/test_ecosystem.yml/badge.svg?branch=${{ github.ref_name }}&numpy=${{ matrix.numpy-version }}&dependent-packages=${{ matrix.dependent-packages }}" >> $GITHUB_OUTPUT
+#jobs:
+#  test_ecosystem:
+#    name: numpy-${{ matrix.numpy-version }}-${{ matrix.dependent-packages }}
+#    runs-on: ubuntu-latest
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        numpy-version: [ 1.25, 2.1 ]
+#        dependent-packages: [ 'ms2deepscore', 'ms2query', 'spec2vec' ]
+#    outputs:
+#      json-path: result.json
+#
+#    steps:
+#      - uses: actions/checkout@v4
+#
+#      - name: Set up Python
+#        uses: actions/setup-python@v5
+#        with:
+#          python-version: '3.11'
+#
+#      - name: Install dependent packages
+#        run: |
+#          python -m pip install --upgrade pip poetry
+#          pip install numpy==${{ matrix.numpy-version }}
+#          pip install ${{ matrix.dependent-packages }}
+#          pip install .
+#          pip check
+#
+#      - name: Show pip list
+#        run: |
+#          pip list
+#
+#      - name: Create Badge URLs
+#        run: |
+#          echo "badge_url=https://github.com/julianpollmann/matchms/actions/workflows/test_ecosystem.yml/badge.svg?branch=${{ github.ref_name }}&numpy=${{ matrix.numpy-version }}&dependent-packages=${{ matrix.dependent-packages }}" >> $GITHUB_OUTPUT
 
 
 
