test ecosystem with artifacts + commentPR

diff --git a/.github/workflows/test_ecosystem.yml b/.github/workflows/test_ecosystem.yml
--- a/.github/workflows/test_ecosystem.yml
+++ b/.github/workflows/test_ecosystem.yml
@@ -1,7 +1,7 @@
 name: Test ecosystem with individual badges
 
 on:
-  push:
+  pull_request:
   workflow_dispatch:
     inputs:
       tag:
@@ -9,19 +9,101 @@ on:
         required: False
         default: ''
 
-
 jobs:
-  test_ecosystem:
-    uses: ./.github/workflows/test_dependency.yml
+  break:
+    runs-on: ubuntu-latest
     strategy:
       fail-fast: false
       matrix:
-        numpy-version: [1.25, 2.1]
-        dependent-packages: ["ms2deepscore", "spec2vec"]
-    with:
-      numpy-version: ${{ matrix.numpy-version }}
-      dependent-packages: ${{ matrix.dependent-packages }}
-    secrets: inherit
+        dependent-packages: [
+          "spec2vec",
+        ]
+#        pkgversion: [latest, stable]
+
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Set up Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: '3.11'
+
+      - name: Install dependent packages
+        run: |
+          python -m pip install --upgrade pip poetry
+          pip install ${{ matrix.dependent-packages }}
+          pip install .
+          pip check
+        continue-on-error: true
+
+      - name: Save compatibility result
+        run: |
+          if [ $? -eq 0 ]; then
+            echo ".. image:: https://img.shields.io/badge/${{ matrix.dependent-packages }}-latest-green :alt: ${{ matrix.dependent-packages }} compatible" >> ${{ matrix.dependent-packages }}.rst
+          else
+            echo ".. image:: https://img.shields.io/badge/${{ matrix.dependent-packages }}-latest-red :alt: ${{ matrix.dependent-packages }} incompatible" >> ${{ matrix.dependent-packages }}.rst
+        shell: bash
+
+      - uses: actions/upload-artifact@v4
+        with:
+          name: pr
+          path: pr/
+
+  upload:
+    needs: break
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+
+      - uses: actions/download-artifact@v4
+        with:
+          name: pr
+          path: pr/
+
+      - run: ls
+      - run: |
+          cd pr
+          echo "| Package name | latest | stable |" > MSG
+          echo "|--|--|--|" >> MSG
+          count=0
+          for file in *
+          do
+            [ "$file" == "NR" ] && continue
+            [ "$file" == "MSG" ] && continue
+            if [ $count == "0" ]; then
+              name=$(echo $file | cut -f1 -d-)
+              echo -n "| $name | "
+            else
+              echo -n "| "
+            fi
+            cat $file
+            if [ $count == "0" ]; then
+              echo -n " "
+              count=1
+            else
+              echo " |"
+              count=0
+            fi
+          done >> MSG
+
+      - uses: actions/upload-artifact@v4
+        with:
+          name: pr
+          path: pr/
+
+
+#jobs:
+#  test_ecosystem:
+#    uses: ./.github/workflows/test_dependency.yml
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        numpy-version: [1.25, 2.1]
+#        dependent-packages: ["ms2deepscore", "spec2vec"]
+#    with:
+#      numpy-version: ${{ matrix.numpy-version }}
+#      dependent-packages: ${{ matrix.dependent-packages }}
+#    secrets: inherit
 
 #jobs:
 #  test_ecosystem:
